config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts do
    collection do
      get 'crawl_url' => 'posts#crawl_url'
      get 'input_url' => 'posts#input_url'
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def input_url
  end

  def crawl_url
    processor = TwitterKorean::Processor.new
    url = params[:src_url] #"http://finance.naver.com/sise/"
    # res = HTTParty.get(url)
    # text = Nokogiri::HTML(res.body)
    text = Nokogiri::HTML(open(url, :allow_redirections => :safe),nil,'utf-8')
    title = text.css('title').text
    tag = text.css("#content").text

    all=Array.new
    tag.split("\n").each do |line|
      l = line.strip
      l.gsub!(/<\/?[^>]*>\",/, "")
      if(l.length > 0)
        all << l
      end
    end
    # kor = /[가-힣a-zA-Z0-9]+/
    # all = text.text.split(' ')
    tk = processor.extract_phrases(all.to_s)
    word=Hash.new(0)

    tk.each do |t|
      if word.has_key? (t)
        word[t] += 1 if t.metadata.pos == :noun
      else
        word.store(t,1) if t.metadata.pos == :noun
      end
    end


    # all.each do |a|
    #     # key = kor.match(a);
    #     unless key.nil?
    #         if word.has_key?(key)
    #             word[key]+=1
    #         else
    #             word.store(key,1)
    #         end
    #     end
    # end
    word = word.sort_by{|k,v| v}.reverse.to_h;
    Post.create(
      title: title,
      src_url: params[:src_url],
      tag1: word.keys[0],
      tag2: word.keys[1],
      tag3: word.keys[2],
      desc: "TEST TEST TEST"
      )
    redirect_to root_path
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :src_url, :tag, :desc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :src_url %><br>
    <%= f.text_field :src_url %>
  </div>
  <div class="field">
    <%= f.label :tag %><br>
    <%= f.text_field :tag %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_field :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Tag1</th>
      <th>Tag2</th>
      <th>Tag3</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.tag1 %></td>
        <td><%= post.tag2 %></td>
        <td><%= post.tag3 %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'URL Path', input_url_posts_path %>

app/views/posts/input_url.html.erb
<%= form_tag(crawl_url_posts_path, method: "get") do %>
  <%= label_tag(:src_url, "URL : ") %>
  <%= text_field_tag(:src_url) %>
  <%= submit_tag("OK") %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Src url:</strong>
  <%= @post.src_url %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @post.tag %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @post.desc %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>